# Generated by Django 5.0.6 on 2024-06-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='person',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
